/*
Created by Franz Zemen 2026-10-03
License Type: UNLICENSED

The generators (visual-styles.prd.md D2, D9, D11, D12). The sample file's output is pinned in full
(snapshot style), so ANY change to the generated text is a deliberate test edit — broken-stock's
agreement test depends on byte-for-byte stability.
*/

import 'mocha';
import {expect} from 'chai';
import {
  cssValueOf, generateCss, generateTailwindTheme, generatorStamp, PACKAGE_VERSION, readGeneratorStamp,
  VisualStylesInvalidError
} from '#project';
import {entry, file, sample} from './fixtures.js';

const SAMPLE_CSS = `/* Generated by @franzzemen/visual-styles-format 9.9.9 (format 1) from visual-styles.json. Do not edit. */

:root {
  --vs-bs-brand-surface: var(--vs-surface);
  --vs-chart-inactive-opacity: 0.2;
  --vs-chart-line-width: 1.5px;
  --vs-loss-text: #8c0b2b;
  --vs-profit-text: #1b5e20;
  --vs-series-1: rgb(41, 121, 255);
  --vs-since-unrealized: var(--vs-series-1);
  --vs-since-unrealized-zero: color-mix(in srgb, var(--vs-since-unrealized) 40%, transparent);
  --vs-surface: #161b22;
}

/* Existing names, taken over (D11): each points at its entry. */
:root {
  --bs-brand-surface: var(--vs-bs-brand-surface);
  --color-loss: var(--vs-loss-text);
  --color-profit: var(--vs-profit-text);
  --color-surface: var(--vs-surface);
}

/* Chart rules (D12): by role class name, never by position. */

.bs-chart-since .bs-s-unrealized .highcharts-graph {
  stroke: var(--vs-since-unrealized);
}

.bs-chart-since .bs-s-unrealized .highcharts-graph {
  stroke-width: var(--vs-chart-line-width);
}

.bs-chart-since .bs-zero-unrealized {
  stroke: var(--vs-since-unrealized-zero);
}
`;

const SAMPLE_THEME = `/* Generated by @franzzemen/visual-styles-format 9.9.9 (format 1) from visual-styles.json. Do not edit. */

@theme inline {
  --color-loss: var(--vs-loss-text);
  --color-profit: var(--vs-profit-text);
  --color-surface: var(--vs-surface);
}
`;

describe('generate', () => {
  describe('generateCss', () => {
    it('produces the pinned output for the sample file', () => {
      expect(generateCss(sample(), {version: '9.9.9'})).to.equal(SAMPLE_CSS);
    });

    it('is independent of entry order (stable ordering)', () => {
      const reversed = {...sample(), entries: [...sample().entries].reverse()};
      expect(generateCss(reversed, {version: '9.9.9'})).to.equal(SAMPLE_CSS);
    });

    it('is independent of field order inside entries', () => {
      const shuffled = {
        entries: sample().entries.map(e => Object.fromEntries(Object.entries(e).reverse())),
        formatVersion: 1
      };
      expect(generateCss(shuffled, {version: '9.9.9'})).to.equal(SAMPLE_CSS);
    });

    it('stamps this package\'s version by default', () => {
      const css = generateCss(sample());
      expect(css.split('\n')[0]).to.equal(generatorStamp());
      expect(readGeneratorStamp(css)).to.deep.equal({version: PACKAGE_VERSION, formatVersion: 1});
    });

    it('reads no stamp from hand-written CSS', () => {
      expect(readGeneratorStamp(':root {}\n')).to.equal(undefined);
      expect(readGeneratorStamp('/* Generated by someone else */')).to.equal(undefined);
    });

    it('emits a follow as var()', () => {
      const f = entry({name: 'b', follow: {target: 'a'}});
      delete f.value;
      expect(cssValueOf(f)).to.equal('var(--vs-a)');
    });

    it('emits an opacity follow as color-mix with transparent', () => {
      const f = entry({name: 'b', follow: {target: 'series-1', opacity: 28}});
      delete f.value;
      expect(cssValueOf(f)).to.equal('color-mix(in srgb, var(--vs-series-1) 28%, transparent)');
    });

    it('emits opacity 0 and fractional opacity exactly', () => {
      const f = entry({name: 'b', follow: {target: 'a', opacity: 0}});
      delete f.value;
      expect(cssValueOf(f)).to.equal('color-mix(in srgb, var(--vs-a) 0%, transparent)');
      f.follow = {target: 'a', opacity: 12.5};
      expect(cssValueOf(f)).to.equal('color-mix(in srgb, var(--vs-a) 12.5%, transparent)');
    });

    it('emits numbers with their unit, or bare for none', () => {
      expect(cssValueOf(entry({name: 'n', kind: 'number', value: 12, unit: 'px'}))).to.equal('12px');
      expect(cssValueOf(entry({name: 'n', kind: 'number', value: 0.875, unit: 'rem'}))).to.equal('0.875rem');
      expect(cssValueOf(entry({name: 'n', kind: 'number', value: 600, unit: 'none'}))).to.equal('600');
    });

    it('emits colour values exactly as written', () => {
      expect(cssValueOf(entry({name: 'a', value: '#1B5E20'}))).to.equal('#1B5E20');
      expect(cssValueOf(entry({name: 'a', value: 'rgb(1 2 3 / 50%)'}))).to.equal('rgb(1 2 3 / 50%)');
    });

    it('omits the legacy and chart sections when there are none', () => {
      const css = generateCss(file(entry({name: 'a'})), {version: '1.0.0'});
      expect(css).to.equal(
        '/* Generated by @franzzemen/visual-styles-format 1.0.0 (format 1) from visual-styles.json. Do not edit. */\n' +
        '\n:root {\n  --vs-a: #ffffff;\n}\n');
    });

    it('emits an empty :root for an empty file', () => {
      expect(generateCss(file(), {version: '1.0.0'})).to.match(/\n:root \{\n\}\n$/);
    });

    it('sorts chart rules by scope, then selector, then property', () => {
      const css = generateCss(file(
        entry({name: 'a', chart: [{scope: '.z', selector: '.a', property: 'fill'}]}),
        entry({name: 'b', chart: [{scope: '.a', selector: '.b', property: 'stroke'}, {scope: '.a', selector: '.b', property: 'fill'}]}),
        entry({name: 'c', chart: [{scope: '.a', selector: '.a', property: 'stroke'}]})
      ), {version: '1.0.0'});
      const rules = css.split('\n').filter(l => l.endsWith('{') && l.startsWith('.'));
      expect(rules).to.deep.equal(['.a .a {', '.a .b {', '.a .b {', '.z .a {']);
      expect(css.indexOf('  fill: var(--vs-b);')).to.be.lessThan(css.indexOf('  stroke: var(--vs-b);'));
    });

    it('writes an element-ending selector as written, after the scope (E21)', () => {
      const css = generateCss(file(
        entry({name: 'a', chart: [{scope: '.bs-chart-index', selector: '.highcharts-button text', property: 'fill'}]})
      ), {version: '1.0.0'});
      expect(css).to.contain('\n.bs-chart-index .highcharts-button text {\n  fill: var(--vs-a);\n}\n');
    });

    it('uses \\n line endings only', () => {
      expect(generateCss(sample())).to.not.contain('\r');
    });

    it('refuses an invalid file and emits nothing', () => {
      expect(() => generateCss(file(entry({name: 'a', value: '#fff; } body { color: red'})))).to.throw(VisualStylesInvalidError);
      expect(() => generateCss({formatVersion: 1, entries: [{name: 'x'}]})).to.throw(VisualStylesInvalidError);
    });

    it('contains no forbidden text for any valid file', () => {
      const css = generateCss(sample());
      const body = css.split('\n').slice(1).join('\n').replace(/\/\* [^*]* \*\//g, '');
      for (const bad of ['url(', '\\', '"', "'", '<', '>']) expect(body, bad).to.not.contain(bad);
    });
  });

  describe('generateTailwindTheme', () => {
    it('produces the pinned @theme inline block for the sample file', () => {
      expect(generateTailwindTheme(sample(), {version: '9.9.9'})).to.equal(SAMPLE_THEME);
    });

    it('is independent of entry order', () => {
      const reversed = {...sample(), entries: [...sample().entries].reverse()};
      expect(generateTailwindTheme(reversed, {version: '9.9.9'})).to.equal(SAMPLE_THEME);
    });

    it('names an entry without a --color- legacy name --color-<css name>', () => {
      const theme = generateTailwindTheme(file(
        entry({name: 'profit.fill', tailwind: true}),
        entry({name: 'brand.accent', legacyName: '--bs-brand-accent', tailwind: true})
      ), {version: '1.0.0'});
      expect(theme).to.contain('  --color-brand-accent: var(--vs-brand-accent);\n  --color-profit-fill: var(--vs-profit-fill);\n');
    });

    it('leaves out entries without tailwind: true', () => {
      const theme = generateTailwindTheme(file(entry({name: 'a'}), entry({name: 'b', tailwind: false})), {version: '1.0.0'});
      expect(theme).to.match(/@theme inline \{\n\}\n$/);
    });

    it('refuses an invalid file', () => {
      expect(() => generateTailwindTheme(file(entry({name: 'a', value: 'red', tailwind: true})))).to.throw(VisualStylesInvalidError);
    });
  });
});
