/*
Created by Franz Zemen 2026-10-03
License Type: UNLICENSED

The CSS generator (broken-stock/doc/prd/visual-styles.prd.md D2, D9, D11, D12).

ONE generator for everybody: the save server writes its output, the panel previews with it, and
broken-stock's agreement test regenerates from the committed JSON and fails if the committed CSS (or
its version stamp) differs. So the output must be DETERMINISTIC — same file in, same bytes out:
  - `:root` variables sorted by CSS name;
  - legacy aliases sorted by legacy name;
  - chart rules sorted by scope, then selector, then property;
  - `\n` line endings, no timestamps, nothing taken from the environment.
Entry order in the JSON does not affect the output.

The generators refuse an invalid file (VisualStylesInvalidError) — they never emit CSS from input
that failed validation.
*/

import {cssVarName, formatNumberValue} from './grammar.js';
import {tailwindThemeName} from './names.js';
import type {Entry, VisualStylesFile} from './types.js';
import {FORMAT_VERSION} from './types.js';
import {assertValidVisualStyles} from './validate.js';
import {PACKAGE_NAME, PACKAGE_VERSION} from './version.js';

function byCodepoint(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** The first line of every generated file, carrying the generator's version (D2). */
export function generatorStamp(version: string = PACKAGE_VERSION): string {
  return `/* Generated by ${PACKAGE_NAME} ${version} (format ${FORMAT_VERSION}) from visual-styles.json. Do not edit. */`;
}

/** Reads the stamp back out of generated text: which generator version and format produced it. */
export function readGeneratorStamp(text: string): {version: string; formatVersion: number} | undefined {
  const firstLine = text.split('\n', 1)[0] ?? '';
  const m = /^\/\* Generated by @franzzemen\/visual-styles-format (\S+) \(format (\d+)\) from visual-styles\.json\. Do not edit\. \*\/$/
    .exec(firstLine);
  return m ? {version: m[1]!, formatVersion: Number(m[2])} : undefined;
}

/** The right-hand side of an entry's `--vs-…` declaration. Assumes a validated entry. */
export function cssValueOf(entry: Entry): string {
  if (entry.follow) {
    const ref = `var(${cssVarName(entry.follow.target)})`;
    return entry.follow.opacity === undefined
      ? ref
      : `color-mix(in srgb, ${ref} ${entry.follow.opacity}%, transparent)`;
  }
  if (entry.kind === 'number') {
    // validated: value is a finite, non-exponent number and unit is present
    return formatNumberValue(entry.value as number, entry.unit!)!;
  }
  return entry.value as string;
}

export interface GenerateOptions {
  /** Override the stamped version. Tests only; the real stamp is this package's version. */
  version?: string;
}

/** The full generated stylesheet for `visual-styles.css`. Throws VisualStylesInvalidError. */
export function generateCss(input: unknown, options: GenerateOptions = {}): string {
  const file: VisualStylesFile = assertValidVisualStyles(input);
  const entries = [...file.entries].sort((a, b) => byCodepoint(cssVarName(a.name), cssVarName(b.name)));
  const out: string[] = [generatorStamp(options.version)];

  out.push('', ':root {');
  for (const e of entries) out.push(`  ${cssVarName(e.name)}: ${cssValueOf(e)};`);
  out.push('}');

  const legacy = entries
    .filter((e): e is Entry & {legacyName: string} => e.legacyName !== undefined)
    .sort((a, b) => byCodepoint(a.legacyName, b.legacyName));
  if (legacy.length > 0) {
    out.push('', '/* Existing names, taken over (D11): each points at its entry. */', ':root {');
    for (const e of legacy) out.push(`  ${e.legacyName}: var(${cssVarName(e.name)});`);
    out.push('}');
  }

  const rules = entries
    .flatMap(e => (e.chart ?? []).map(r => ({...r, name: e.name})))
    .sort((a, b) => byCodepoint(a.scope, b.scope) || byCodepoint(a.selector, b.selector) || byCodepoint(a.property, b.property));
  if (rules.length > 0) {
    out.push('', '/* Chart rules (D12): by role class name, never by position. */');
    for (const r of rules) {
      out.push('', `${r.scope} ${r.selector} {`, `  ${r.property}: var(${cssVarName(r.name)});`, '}');
    }
  }
  return out.join('\n') + '\n';
}

/**
 * The Tailwind v4 theme block for `tailwind: true` colour entries (D11):
 *
 *   @theme inline {
 *     --color-profit: var(--vs-profit);
 *   }
 *
 * `inline` is deliberate (tailwindcss 4.3.3): utilities are written with the value itself —
 * `.text-profit { color: var(--vs-profit) }` — so a live edit of `--vs-profit` repaints Tailwind
 * utilities, `var(--color-profit)` users and charts alike. Tailwind still writes its own copy of
 * `--color-profit` inside `@layer theme` (measured in broken-stock's build, E3); that is harmless:
 * it holds the same `var(--vs-profit)`, and the generated CSS's legacy alias sits outside any
 * layer, so it wins whatever the load order. Throws VisualStylesInvalidError.
 */
export function generateTailwindTheme(input: unknown, options: GenerateOptions = {}): string {
  const file: VisualStylesFile = assertValidVisualStyles(input);
  const lines = file.entries
    .filter(e => e.tailwind === true && e.kind === 'colour')
    .map(e => ({theme: tailwindThemeName(e.name, e.legacyName), css: cssVarName(e.name)}))
    .sort((a, b) => byCodepoint(a.theme, b.theme))
    .map(t => `  ${t.theme}: var(${t.css});`);
  return [generatorStamp(options.version), '', '@theme inline {', ...lines, '}'].join('\n') + '\n';
}
