/*
GENERATED by scripts/stamp-version.mjs from package.json — do not edit.
License Type: UNLICENSED
*/

export const PACKAGE_NAME = '@franzzemen/visual-styles-format';
export const PACKAGE_VERSION = '1.0.0';
