// Writes src/project/version.ts from package.json.
//
// Runs as the npm "version" lifecycle script, i.e. inside `npm version` AFTER package.json is bumped
// and BEFORE npm's commit, during bs.patch/minor/major. It then rebuilds (tsc -b) so the published
// out/project/version.js carries the new version, and stages version.ts so the bump commit includes it.
// The const exists because the generator also runs in the browser (the Visual Styles panel), where
// reading package.json at run time is not possible. A test fails if the const and package.json differ.
import {readFileSync, writeFileSync} from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const text = `/*
GENERATED by scripts/stamp-version.mjs from package.json — do not edit.
License Type: UNLICENSED
*/

export const PACKAGE_NAME = '${pkg.name}';
export const PACKAGE_VERSION = '${pkg.version}';
`;
writeFileSync(new URL('../src/project/version.ts', import.meta.url), text);
console.log(`stamped ${pkg.name} ${pkg.version}`);
